### ISSUE TITLE
It's possible the see the answer of classic mode by looking at network tab on devtools

### ISSUE THREAD

**Issue by AngeloTadeucci** [MorningLit/maple-wordle-public#4]
For fun I was looking how the website worked and noticed that it's possible to see the answer using the network tab, idk how you have it set up but it should be possible to not request the image until the answer is correct

Thanks for making this amazing website :D

![image](https://github.com/MorningLit/maple-wordle-public/assets/15664821/32cfac25-3628-444d-b2a9-8572d162887e)

**Comment by MorningLit** [comment]
Yea this happens because I need to get the image to calculate it's width and height, I think this can't be avoided unless I hardcode all the image's width and height in the database so I will leave as it is.

PS: And there is a another way to cheat easily if you wanted to 😝, similar to how other wordle websites are done (Just that they encode + salt their values and I don't care all that much). It can be a fun "hacking" exercise for you 🙈
